//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CgssEventTool.Localization.Resources.Layout {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventCalculatorPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventCalculatorPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CgssEventTool.Localization.Resources.Layout.EventCalculatorPageResources", typeof(EventCalculatorPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        internal static string CollectedItemHeader {
            get {
                return ResourceManager.GetString("CollectedItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected Items.
        /// </summary>
        internal static string CollectedItemLabel {
            get {
                return ResourceManager.GetString("CollectedItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points from item.
        /// </summary>
        internal static string CollectedPointsFromItemLabel {
            get {
                return ResourceManager.GetString("CollectedPointsFromItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points using item.
        /// </summary>
        internal static string CollectedPointsUsingItemLabel {
            get {
                return ResourceManager.GetString("CollectedPointsUsingItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event hours.
        /// </summary>
        internal static string EventHoursLabel {
            get {
                return ResourceManager.GetString("EventHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1x (19 Stem).
        /// </summary>
        internal static string MultiplierOneLabel {
            get {
                return ResourceManager.GetString("MultiplierOneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x (38 Stem).
        /// </summary>
        internal static string MultiplierTwoLabel {
            get {
                return ResourceManager.GetString("MultiplierTwoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural recover.
        /// </summary>
        internal static string NaturalRecoverLabel {
            get {
                return ResourceManager.GetString("NaturalRecoverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLv.
        /// </summary>
        internal static string PlayerLevelLabel {
            get {
                return ResourceManager.GetString("PlayerLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultSectionHeader {
            get {
                return ResourceManager.GetString("ResultSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star no..
        /// </summary>
        internal static string StarTotalLabel {
            get {
                return ResourceManager.GetString("StarTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Points Calculator.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points.
        /// </summary>
        internal static string TotalPointsLabel {
            get {
                return ResourceManager.GetString("TotalPointsLabel", resourceCulture);
            }
        }
    }
}
